dry-run: null
hookfiles: null
language: nodejs
sandbox: false
#server: php artisan serve
server-wait: 5
init: false
custom: {}
names: false
only: []
reporter: null
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: blueprint.md
endpoint: 'http://localhost:3000'
